#################################
# Jesus Narvaez
# Makefile for CS 325 Homework 4
# February 21st, 2020
# Executes mstEuclid.py on given file
#################################

PYTHON = python3

SRC_1 = mstEuclid.py

#Change file to read from here!
TXT_1 = graph4.txt

mst:
	clear
	${PYTHON} ${SRC_1} ${TXT_1}

all: mst
