#################################
# Jesus Narvaez
# Makefile for CS 325 Homework 2
# January 24th, 2020
# Compiles and creates executables
# for mergesort3.cpp merge3Time.cpp
#################################

PYTHON = python3

SRC_1 = knapsack.py

knapsack:
	${PYTHON} ${SRC_1}
	@echo Built ${SRC_1}

all: knapsack
